### ISSUE TITLE
Inconsistency between schematic and actual board

### ISSUE THREAD

**Issue by irdc** [tinyvision-ai-inc/UPduino-v3.0#10]
Looking at the schematic vs the actual board, there appears to be an inconsistency regarding the location of the 12MHz output. From the USB connector on downwards, the pins on the board are marked as "10", "12M", "GND", "12", etc. However, according to the schematic it's "10", "GND", "12M", "12" (that is: 12M and GND are swapped).

Which is the correct one?

**Comment by vr2045** [comment]
Please see the https://upduino.readthedocs.io/en/latest/features/specs.html for the pinout. Initial versions of the UPduino had a silkscreen error and the silkscreen was blacked out with a marker to avoid confusion. This should have been corrected on later versions of the board.
