### ISSUE TITLE
Full-scale RISC-V SoC for ice40 up5k FPGA

### ISSUE THREAD

**Issue by stnolting** [tinyvision-ai-inc/UPduino-v3.0#4]
Great work! I really like the UPduino boards! 

Interested in yet another RISC-V SoC for the Board? ;)

https://github.com/stnolting/neorv32

It is a full-scale `rv32imc` + *privileged architecture* RISC-V processor with SPI, I²C, PWM, GPIO, TIMER and a Watchdog. The whole SoC perfectly fits in a ice40 up5k FPGA and runs at 22MHz (tested on UPduino v2.0). The project comes with some example programs and a bootloader capable of storing/booting an executable from the on-board FPGA configuration flash.

Best regards

**Comment by vr2045** [comment]
Thats very interesting, will try it out and perhaps distribute this as part of the startup program on the board!

**Comment by stnolting** [comment]
Thank you very much! :)
Feel free to contact me if you need any help.
