### ISSUE TITLE
Silkscreen swapped on J3 pins 7 and 8 (12M and GND)

### ISSUE THREAD

**Issue by radicale** [tinyvision-ai-inc/UPduino-v3.0#8]
Noticed that the schematic did not match the silkscreen on LHS (J3) pins 7 and 8.  Quick test shows that the issue is with the silkscreen.

**Comment by radicale** [comment]
Nevermind.  Seems like it's been already fixed in the repo.

**Comment by vr2045** [comment]
Thanks for being proactive and filing this in the first place! Enjoy the
board and let me know if you need anything.
